# 워크 플로우의 이름 설정
name: RUN_UNIT_TEST

# 워크 플로우의 트리거 설정 (develop브랜치에 대한 push,pr에 대해 처리한다)
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

# 워크 플로우에서 실행될 작업 정의
jobs:
  build:
    # 작업을 실행할 운영체제 설정
    runs-on: ubuntu-latest

    # 병렬 실행 전략 설정 (Node사용)
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # 각 단계 설정
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
